server:
  port: 8761

spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: 172.30.0.7
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/











