version: "3.8"

services:

  discovery-server:
    image: jcaboclo/discovery-server:latest
    ports:
      - "8761:8761"
    mem_limit: 700m
    networks:
      - jcaboclo-network

  spring-cloud-config-server:
    image: jcaboclo/spring-cloud-config-server:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - jcaboclo-network

  api-gateway:
    image: jcaboclo/api-gateway:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - jcaboclo-network

  inventory-service:
    image: jcaboclo/inventory-service:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - jcaboclo-network
    
  product-service:
    image: jcaboclo/product-service:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - jcaboclo-network

  order-service:
    image: jcaboclo/order-service:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - jcaboclo-network
    
networks:
  jcaboclo-network: